#!/bin/bash -e

me=$(basename $0)

# setup logging
LOG=/dev/stderr
log(){
  echo $(date +%FT%TZ): $me: "$@" >>"$LOG"
}
chlog(){
  [ -w "$1" ] || log "\`$1' not writable, using stderr instead" && LOG="$1"
}
chlog /var/log/twitter.log

error(){
  local code="$1"
  shift
  echo "$@" >>/dev/stderr
  exit "$code"
}

[ $# != 0 ] || error 1 "The lower threshold argument is expected"
thresholdLO="$1"
shift
[ $# != 0 ] || error 1 "The upper threshold argument is expected"
thresholdHI="$1"
shift

getrate(){
  twitter-rate-limit | json-'select' '/"remaining_hits"'
}

rate=$(getrate)
if [ $rate -gt $thresholdLO ]; then
  log "OK: $rate"
  exec "$@"
fi

log "Too low: $rate"
while [ $rate -lt $thresholdHI ]; do
  log "Waiting 10min..."
  sleep 10m
  rate=$(getrate)
done
log "OK: $rate"
exec "$@"
