#!/bin/bash -e

# setup logging
LOG=/dev/stderr
log(){
  echo $(date +%FT%TZ): twitter-with-cursor: "$@" >>"$LOG"
}
chlog(){
  [ -w "$1" ] || log "\`$1' not writable, using stderr instead" && LOG="$1"
}
chlog /var/log/twitter.log

error(){
  local code="$1"
  shift
  echo "$@" >>/dev/stderr
  exit "$code"
}

field="$1"
[ -n "$field" ] || error 1 "The non-cursor field name argument is expected"
shift
cmd=( "$@" )
[ $# != 0 ] || error 1 "The command to run is expected"

tmp=$(mktemp)
cursor=-1

step(){
  "${cmd[@]}" "cursor=$cursor" >"$tmp"
  cursor=$(json-select '/"next_cursor"' <"$tmp")
  log "next_cursor: $cursor"
  json-select /\""$field"\" 2>/dev/null <"$tmp"
  rm -f "$tmp"
}

echo -n '['
step
while [ "$cursor" != 0 ]; do
  echo -n ','
  step
done
echo ']'
