#!/bin/bash -e
b=/var/spool/twitter/hourly-backup/$(date +%Y-%m-%d_%H)
try-10-times                       \
  respect-twitter-rate-limit 50 60 \
    twitter-friends-timeline       \
 >"$b".1line.json
json-wrap <"$b".1line.json >"$b".json
rm "$b".1line.json
[ -s "$b".json ] || rm "$b".json
