#!/bin/bash -e

error(){
  local code="$1"
  shift
  echo "$@" >>/dev/stderr
  exit "$code"
}

[ $# != 0 ] || error 1 "The page count is expected"
page_count=$(( $1 ))
shift

[ $# != 0 ] || error 1 "The command to run is expected"

echo -n '['
"$@" page=1
page=2
while [ $page -le $page_count ]; do
  echo -n ','
  "$@" page=$page
  page=$(($page + 1))
done
echo ']'
